### ISSUE TITLE
If the same page has the same file name, the file will be overwritten and saved.

### ISSUE THREAD

**Issue by oku-kaz** [bitbybyte/fantiadl#55] opened 2021-01-29 11:21 UTC
For articles with multiple billing plans on the same page, the owner can upload different files with the same filename, but in that case only the last file on the page will be saved.
I can work around this by using use-server-filenames, but please do not overwrite each of them if possible.
Thank you.

**Comment by bitbybyte** [comment] 2021-01-30 08:20
Server filenames were forced for all files starting with v1.7 (https://github.com/bitbybyte/fantiadl/commit/e46a0c9a2ca1a1d39f3355eb85585fc56fc54885). Are you using the latest version? If so, can you show me a post where you're having problems?

**Comment by bitbybyte** [comment] 2021-02-01 23:51
@oku-kaz See above.

**Comment by bitbybyte** [comment] 2021-02-09 00:33
Closing as I can't reproduce. If you can provide more info, please reply here and I'll take a look.

**Closed by bitbybyte** 2021-02-09 00:33 UTC
